### ISSUE TITLE
Having issues in 10.8.0-beta2 Pre-release with jellyfin-ffmpeg 4.4.1-4

### ISSUE THREAD

**Issue by ZeVince** [pdulvp/jellyfin-qnap#11]
Video/Audio/Subtitles stream infos not extracted for new media

New media not playing in jellyfin-media-player v1.7.0 Prerelease 4 

10.8.0-beta2 with jellyfin-ffmpeg_4.4.1-4 from 10.8.0-beta1 is working fine for indexing and playing new media

Just me ?

**Comment by pdulvp** [comment]
This is fixed thanks to [@nyanmisaka](https://github.com/nyanmisaka) and available on the latest packaging release [10.8.0-beta2](https://github.com/pdulvp/jellyfin-qnap/releases/tag/10.8.0-beta2-fixes11)
