### ISSUE TITLE
10.10.0版本 有bug

### ISSUE THREAD

**Issue by tangyl2000** [pdulvp/jellyfin-qnap#111]
`Log recorded at Mon Nov  4 11:05:23 HKT 2024

=== df output ===
Filesystem                Size      Used Available Use% Mounted on
none                    400.0M    351.9M     48.1M  88% /
devtmpfs                  7.7G      4.0K      7.7G   0% /dev
tmpfs                    64.0M     64.0M         0 100% /tmp
tmpfs                     7.7G    172.0K      7.7G   0% /dev/shm
tmpfs                    16.0M         0     16.0M   0% /share
/dev/mmcblk0p5            7.7M     51.0K      7.7M   1% /mnt/boot_config
tmpfs                    16.0M         0     16.0M   0% /mnt/snapshot/export
/dev/md9                493.5M    172.1M    321.4M  35% /mnt/HDA_ROOT
cgroup_root               7.7G         0      7.7G   0% /sys/fs/cgroup
/dev/mapper/vg1-lv1312
                          1.1G      1.4M      1.1G   0% /mnt/pool1
/dev/mapper/vg2-lv1313
                        740.9M    800.0K    740.2M   0% /mnt/pool2
/dev/mapper/cachedev1
                         10.1T      2.9T      7.2T  28% /share/CACHEDEV1_DATA
/dev/mapper/cachedev2
                          7.1T    269.0G      6.8T   4% /share/CACHEDEV2_DATA
/dev/md13               416.7M    379.2M     37.5M  91% /mnt/ext
tmpfs                    32.0M     27.2M      4.8M  85% /samba_third_party
tmpfs                     4.0K         0      4.0K   0% /tmp/default_dav_root
tmpfs                    48.0M     32.0K     48.0M   0% /share/CACHEDEV1_DATA/.samba/lock/msg.lock
tmpfs                    16.0M         0     16.0M   0% /mnt/ext/opt/samba/private/msg.sock
tmpfs                    10.0M         0     10.0M   0% /tmp/wfm
tmpfs                   100.0K         0    100.0K   0% /share/CACHEDEV1_DATA/Container/container-station-data/lib/lxd/shmounts
tmpfs                   100.0K         0    100.0K   0% /share/CACHEDEV1_DATA/Container/container-station-data/lib/lxd/devlxd
tmpfs                    64.0M     64.0M         0 100% /share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp
hdsfusemnt              400.0M    351.9M     48.1M  88% /share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/share
none                      7.7G         0      7.7G   0% /share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/sys/fs/cgroup
udev                      7.7G      4.0K      7.7G   0% /share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/dev
none                      7.7G         0      7.7G   0% /share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/dev/shm
tmpfs                     7.7G         0      7.7G   0% /share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/run
none                      7.7G         0      7.7G   0% /share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/run/lock
none                      7.7G         0      7.7G   0% /share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/run/user
overlay                  10.1T      2.9T      7.2T  28% /share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/21bb11c84f7015a5618fe7e24b9769f6b8393ff484f85b2bbc1f5dc80ba10747/merged
overlay                  10.1T      2.9T      7.2T  28% /share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/a4208f5c8c89d86378897cf4d91c1cea48479fa09728f613f7d83b379665170b/merged
overlay                  10.1T      2.9T      7.2T  28% /share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/25370ccfee870588700555fe9c6ca101e35ef6dd181b5827d29c1c79b09ea59e/merged
overlay                  10.1T      2.9T      7.2T  28% /share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/f588c413dccf31181efdce7fe7d96a29ab4f0d27684ee00f02463c7e61fdf808/merged
overlay                  10.1T      2.9T      7.2T  28% /share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/a32915b15eaf68f32517b936227398162d5432a96d13ebabff9f055901b13264/merged
overlay                  10.1T      2.9T      7.2T  28% /share/CACHEDEV1_DATA/.qpkg/container-station/system-docker/overlay2/554b10b341834ce100d56e34a9a7d239142bf6314c4ec4427b079a609f951b62/merged
overlay                  10.1T      2.9T      7.2T  28% /share/CACHEDEV1_DATA/.qpkg/container-station/system-docker/overlay2/e3b5d9d7db1288a0576e3f4198477eb363d50cddff2b0b11f21ffc3cda00da97/merged
overlay                  10.1T      2.9T      7.2T  28% /share/CACHEDEV1_DATA/.qpkg/container-station/system-docker/overlay2/c35da2fee9f8395ad6dba9a477a1df4153078f4a024b4bdca7cac530bd576437/merged
/dev/mapper/vg1-snap10001
                         10.1T      2.9T      7.2T  28% /mnt/snapshot/1/10001
/dev/mapper/vg1-snap10002
                         10.1T      2.9T      7.2T  28% /mnt/snapshot/1/10002
overlay                  10.1T      2.9T      7.2T  28% /share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/overlay2/fc2d4b268d4f1c47e75fcfd0c8b416ba94b2dd51fe4ac22efbd562ed7b21cb6b/merged

=== du output ===
1.5M	/tmp/jellyfin/skia_03ebc3e5-6ebc-4396-981b-92ea8c8e82bc.jpg
1.2M	/tmp/jellyfin/skia_54808c66-5ee9-4cfc-a976-b31e562b6d69.jpg
1.5M	/tmp/jellyfin/skia_f77344df-5e78-40e1-9c00-09c4af2fa47c.jpg
1.8M	/tmp/jellyfin/skia_a54b6843-efa2-4474-9b6e-d6a7efd84f1f.jpg
1.5M	/tmp/jellyfin/skia_604a67e7-d1ab-467c-b0d9-6d35ca91f031.jpg
1.5M	/tmp/jellyfin/skia_b878068c-aa64-4ab2-a514-baf66f53bfa0.jpg
1.2M	/tmp/jellyfin/skia_5e634368-0328-43cf-a559-6671f4eba98b.jpg
1.2M	/tmp/jellyfin/skia_4346bf38-26bc-472d-a7ee-cfce2b00181e.jpg
1.8M	/tmp/jellyfin/skia_8cde4a05-9354-42f5-9698-91875d989d18.jpg
1.8M	/tmp/jellyfin/skia_4e29008e-c123-4d6c-a494-fcaf95246086.jpg
1.5M	/tmp/jellyfin/skia_d86510a5-2c2f-414e-8920-cf0d4379ac69.jpg
1.5M	/tmp/jellyfin/skia_ab7fbbaf-cc06-4bef-a60c-0d2abf79b02f.jpg
1.2M	/tmp/jellyfin/skia_fd7d1566-46ae-4711-88cd-54b92ea6ad81.jpg
1.2M	/tmp/jellyfin/skia_9b23ad52-0cb8-479b-92d4-9f9185dd6c58.jpg
1.8M	/tmp/jellyfin/skia_a9d6ad32-5e2a-47f8-8c66-d31eb99e4b85.jpg
62M	/tmp/jellyfin
64M	/tmp
1.5M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_03ebc3e5-6ebc-4396-981b-92ea8c8e82bc.jpg
1.2M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_54808c66-5ee9-4cfc-a976-b31e562b6d69.jpg
1.5M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_f77344df-5e78-40e1-9c00-09c4af2fa47c.jpg
1.8M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_a54b6843-efa2-4474-9b6e-d6a7efd84f1f.jpg
1.5M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_604a67e7-d1ab-467c-b0d9-6d35ca91f031.jpg
1.5M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_b878068c-aa64-4ab2-a514-baf66f53bfa0.jpg
1.2M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_5e634368-0328-43cf-a559-6671f4eba98b.jpg
1.2M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_4346bf38-26bc-472d-a7ee-cfce2b00181e.jpg
1.8M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_8cde4a05-9354-42f5-9698-91875d989d18.jpg
1.8M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_4e29008e-c123-4d6c-a494-fcaf95246086.jpg
1.5M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_d86510a5-2c2f-414e-8920-cf0d4379ac69.jpg
1.5M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_ab7fbbaf-cc06-4bef-a60c-0d2abf79b02f.jpg
1.2M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_fd7d1566-46ae-4711-88cd-54b92ea6ad81.jpg
1.2M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_9b23ad52-0cb8-479b-92d4-9f9185dd6c58.jpg
1.8M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin/skia_a9d6ad32-5e2a-47f8-8c66-d31eb99e4b85.jpg
62M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp/jellyfin
64M	/share/CACHEDEV1_DATA/.qpkg/MediaSignPlayer/CodexPackExt/tmp
`
以上为威联通464c2中jellyfin 10.10.0的bug日志，qnap系统会报错：
![image](https://github.com/user-attachments/assets/7e5f052c-50a6-46cf-b6d9-24026801c6aa)
![image](https://github.com/user-attachments/assets/1d3d1619-514c-443f-9edf-325dfb454b31)
因为威联通的系统默认分配的/tmp容量为64M，只要图片一多，就会报RAMDisk /或/tmp容量不足错误。
而我的群晖默认分配/tmp容量为16G。

但删除这些.jpg文件后就正常。

刚看官方新发布的版本10.10.1，貌似解决了这个问题：
![1730713846424](https://github.com/user-attachments/assets/3ec15cb7-d1d5-4173-91d4-7a8cda13b8e6)
跪求大神更新10.10.1，万分感谢！

**Comment by pdulvp** [comment]
AH yes, they have moved the temporary folder to /tmp.
Will see with 10.10.1 🤞

**Comment by tangyl2000** [comment]
> AH yes, they have moved the temporary folder to /tmp. Will see with 10.10.1 🤞

太感谢大神了！！！

**Comment by tangyl2000** [comment]
Thank you very much!
I have got version 10.10.1~~
Please close this issue~
Thanks again~~~
