### ISSUE TITLE
Installation stopped on QTS 5.0.02034

### ISSUE THREAD

**Issue by TBS-453DX** [pdulvp/jellyfin-qnap#17]
With last QTS 5.0.02034
On a TBS-453DX (Intel J4105 CPU)
Installation stopped with a message requesting to downgrade the firmware version.

**Comment by pdulvp** [comment]
Oh I see, 
It's a 5.0.1 now.
https://www.qnap.com/fr-fr/release-notes/qts/overview/5.0.1

**Comment by AlfaRivieor** [comment]
with 5.0.1.2034 public Beta on TS453Bmini,when i install the latest 1.0.8.0b3 fix17 still stopped and ask me to downgrade to 5.0.0
