### ISSUE TITLE
Changing the port doesn't propagate to the QNAP app launch settings

### ISSUE THREAD

**Issue by mattbaker-digital** [pdulvp/jellyfin-qnap#25]
I changed the networking port in the Jellyfin dashboard, saved the settings and restarted the app/service from the QNAP App Center. The launcher tries to use the default/old port instead of the new one. If I manually specify the new port in the URL it works as expected.

**Comment by gummykage** [comment]
SSH into your qnap and look for /etc/config/qpkg.conf. Change the port in this file, Close App Center, Reopen it and click open on jellyfin and it will update the other shortcuts.

![image](https://user-images.githubusercontent.com/9695713/191639194-e3714618-501b-4494-9d90-b2298997a182.png)

**Comment by mattbaker-digital** [comment]
@gummykage Thanks. Good to know.

**Comment by pdulvp** [comment]
Hi,
Now if you change the port on Jellyfin administration, the file qpkg.conf is updated accordingly at jellyfin startup.
