### ISSUE TITLE
Error message saying that server is on 10.7.7 despite upgrade to 10.8.7

### ISSUE THREAD

**Issue by TBS-453DX** [pdulvp/jellyfin-qnap#32]
On a Qnap TBS-453DX the version 10.8.7 has been loaded. On an Android box LEAP-S1, app jellyfin-androidtv 0.14.5 release, the app gives an error message saying that the server uses the old version 10.7.7 and must be upgraded to 10.8.1.

Server app stopped on the QNAP and relaunched; QNAP rebooted: no changes, the error message message is still raised.
Is there a buffer or a file, not correctly cleaned during the upgrade, to delete?

**Comment by pdulvp** [comment]
Fixed.
