### ISSUE TITLE
I have the same issue 

### ISSUE THREAD

**Issue by waynepaulward** [pdulvp/jellyfin-qnap#36]
Hi i have the same issue with no fanart 
Also i have iptv installed and it used to show a preview of what was on the channel but it doesnt do this now. Does this bug still apply on the version in testing the new .1 version

**Comment by waynepaulward** [comment]
I switched back to the qnap store version its older but doesnt have the image bug on the icons please can you update me when this is fixed ill switch back - but seems like no communication here which is sad 😢

**Comment by pdulvp** [comment]
see https://github.com/pdulvp/jellyfin-qnap/issues/28
