### ISSUE TITLE
Is there any plan to adapt to QTS5.1?

### ISSUE THREAD

**Issue by cooshare** [pdulvp/jellyfin-qnap#48]
App Status Change	[App Center] Failed to start jellyfin. QTS does not support this jellyfin version. Check for updates in "App Center" or on the official app website.

**Comment by wjz304** [comment]
+1

**Comment by menstry** [comment]
+1

**Comment by netrapture** [comment]
+1

**Comment by pdulvp** [comment]
shall be ok now
