### ISSUE TITLE
do not work with qts 5.1.0 yet

### ISSUE THREAD

**Issue by densu90** [pdulvp/jellyfin-qnap#54]
hi
do not work with qts 5.1.0 yet:

Warning	2023-07-10	18:22:00	System	127.0.0.1	---	---	App Center	App Status Change	[App Center] Failed to start jellyfin. QTS does not support this jellyfin version. Check for updates in "App Center" or on the official app website.

from here: https://pdulvp.github.io/qnap-store/repos.xml

**Comment by adonetgithub** [comment]
I updated my QNAP nas to QTS 5.1.0 yesterday and Jellyfin 10.8.9-1 doesn't work as mentioned above. Any suggestions what I can do, or should I just wait for an update of Jellyfin?

**Comment by pdulvp** [comment]
Shall be ok now. 
The store was not up to date with the latest release from may.
