### ISSUE TITLE
[Feature Request] Rename QPKG from 'jellyfin' to 'Jellyfin'

### ISSUE THREAD

**Issue by OdinVex** [pdulvp/jellyfin-qnap#56]
Could the QPKG front-end be renamed from jellyfin to Jellyfin (App Center). I think that was an oversight? It affects which folder name it uses in .qpkg, such as Jellyfin from QNAPClub (making migration more difficult).

**Comment by pdulvp** [comment]
It was done on purpose as this package is not compatible with the QnapClub one as I don't have it, I don't know what's in it.
Not sure if its possible now as it will break the current installations
