### ISSUE TITLE
QNAP won't start Jellyfin 10.8.9-1 after firmware update to 5.1.1.2491

### ISSUE THREAD

**Issue by WayneColony** [pdulvp/jellyfin-qnap#58]
Just updated QNAP TS-453Be to firmware ver 5.1.1.2491(20230815) from ver 5.0.1.2376(20230421) and now Jellyfin 10.8.9-1 will not start. 

The log gives the error: 
_"Failed to start jellyfin. QTS does not support this jellyfin version. Check for updates in "App Center" or on the official app website."_

**Comment by zuicy** [comment]
update to Jellyfin 10.8.10，it works to me

**Comment by WayneColony** [comment]
More research and found this link: https://pdulvp.fr/qstore.html 
This has instructions for adding alternative app stores, one for stable releases, and one for prereleases.

Not sure if it would have been better to just install the newer version without removing the previous version but I uninstalled and then reinstalled the updated version. And the 10-8.10 version resolved the "no start" issue.

**Comment by zuicy** [comment]
> > 更新到 Jellyfin 10.8.10，对我有用
> 
> 你是怎么更新的？它在 QNAP 的应用中心中显示没有可用的更新，快速的 Google 搜索仅显示如何安装。 您是卸载并重新安装还是只是在早期版本的基础上安装？

https://github.com/pdulvp/jellyfin-qnap/releases
you can also download here，maybe the https://pdulvp.fr/qstore.html version update slower than github version

**Comment by zuicy** [comment]
> > update to Jellyfin 10.8.10，it works to me
> 
> How did you update it? It shows no available update in QNAP's App Center and a quick Google search just shows how to install. Did you uninstall and reinstall or just install over the top of the earlier version?

also just install over the earlier version is ok，dont need uninstalled first
