### ISSUE TITLE
Is it possible to modify the contents of `qpkg.cfg` without rebuilding the app?

### ISSUE THREAD

**Issue by sepsol** [pdulvp/jellyfin-qnap#71]
I want to change where the app is accessible in my QNAP's web interface. Specifically, I want to modify the [`QPKG_WEBUI`](https://github.com/pdulvp/jellyfin-qnap/blob/578c7f700e9f1b2d1d956afc40bd75c538c53e8f/jellyfin/qpkg.cfg#L35) and [`QPKG_WEB_PORT`](https://github.com/pdulvp/jellyfin-qnap/blob/578c7f700e9f1b2d1d956afc40bd75c538c53e8f/jellyfin/qpkg.cfg#L37C1-L37C14) variables so that I can reuse the same SSL certificate I have on my main web UI for Jellyfin as well. 

Currently I can't go to `https://mydomain.local:8096` because it gives a `ERR_SSL_PROTOCOL_ERROR` error since the port/process is different from what was specified on my QNAP's certificate (which referred to `443`/https by default). I have to disable https and use `http://mydomain.local:8096` only for this app.

I was wondering whether it is possible to change variables I mentioned at the beginning so that I can use the app on `https://mydomain.local/jellyfin` or `https://mydomain.local/media` or something similar. I know this would fix the issue because QuMagie runs on `https://mydomain.local/qumagie` and it works fine.

Thanks in advance for the help and the great app!

**Comment by pdulvp** [comment]
Hi, 
It is now possible programmatically at jellyfin startup.
You can add a new file that do some additional stuff.
e.g https://github.com/pdulvp/jellyfin-qnap/blob/master/packaging/shared/user-config.sh.sample
