### ISSUE TITLE
10.9.0版本更新后存在首页空白的问题，以及临时解决方案

### ISSUE THREAD

**Issue by moseeking** [pdulvp/jellyfin-qnap#79]
设备：TS-453D
上个版本([10.8.13-1](https://github.com/pdulvp/jellyfin-qnap/releases/tag/108131.108131.5142_58370fcc))直接安装更新后，存在直接打开首页是空白的问题，找到jellyfin下相关联的[issue](https://github.com/jellyfin/jellyfin/issues/11533)，希望能同步解决下。

临时解决方案：打开`qpkg安装目录/jellyfin/jellyfin/bin/jellyfin.runtimeconfig.json`文件，将`"System.Globalization.Invariant": true`改为`false`，jellyfin控制台里关闭服务器，然后nas重新打开jellyfin服务即可，无须重新安装。
![image](https://github.com/pdulvp/jellyfin-qnap/assets/17546266/50ecfad1-100e-4cc9-ac1d-33c7849f88f9)

**Comment by pdulvp** [comment]
Oh ok,
It's probably due to a non english qnap platform.
When it was on false it was raising another issue that was preventing Jellyfin to launch.
https://github.com/pdulvp/jellyfin-qnap/issues/13

I will try without it then if it is now working properly.

**Comment by Izumiko** [comment]
`System.Globalization.Invariant` seems to be invalid since 10.9 according to [Breaking Changes](https://jellyfin.org/posts/jellyfin-release-10.9.0/#key-release-notesbreaking-changes)
