### ISSUE TITLE
Repository icon pointing to non-existing URLs

### ISSUE THREAD

**Issue by UniverseDevel** [pdulvp/jellyfin-qnap#96]
In your repository links for QNAP Jellyfin Icons are pointing to URLs that do not exist:

![image](https://github.com/user-attachments/assets/61d06df4-5937-452c-98ba-ef3116ccf558)

https://raw.githubusercontent.com/pdulvp/jellyfin-qnap/1096.1096.6017.5143-c_87512fb3/jellyfin/icons/jellyfin.gif -> 404: Not Found
https://raw.githubusercontent.com/pdulvp/jellyfin-qnap/1096.1096.6017.5143-c_87512fb3/jellyfin/icons/jellyfin_80.gif -> 404: Not Found

This results in missing icon in QNAP app store:

![image](https://github.com/user-attachments/assets/967cb934-bb6b-4ebe-93ae-d17fbfbee72b)

Note: Other applications works fine only plain Jellyfin app has this problem (HD works as well).

**Comment by pdulvp** [comment]
Nice catch!
