### ISSUE TITLE
使用商店安装10.9.6，更新10.9.9失败

### ISSUE THREAD

**Issue by zw900** [pdulvp/jellyfin-qnap#99]
CN:提示更新至10.9.9-e版本，点击更新后虽然右上角显示更新已完成，但商店仍然提示需要更新。
设备：453Bmini
版本：5.1.8.2823
已尝试重启，没有效果

EN:Prompted to update to version 10.9.9-e, and after clicking update the store still prompts for an update even though the top right corner shows that the update is complete.    
Device: 453Bmini
Version: 5.1.8.2823
Tried rebooting, no effect

![image](https://github.com/user-attachments/assets/1e0b8274-d23e-43f0-8800-933b8df79113)

**Comment by UniverseDevel** [comment]
Can confirm same behavior.
![image](https://github.com/user-attachments/assets/f43c5065-5ff7-4ff9-8ca7-7f074046756f)
I updated to 10.9.9 and after update I am still prompted for update as apparently I am not on 10.9.9-e version but update will go trough and I will never end on such version.

**Comment by oxivanisher** [comment]
I have the same problem. Getting a email every day from my nas that it is not able to update the package.

**Comment by pdulvp** [comment]
shall be ok now
